import argparse
from pathlib import Path

import matplotlib.pyplot as plt
import torch

from fm_minimal import MLPVelocity, euler_solve, sample_eight_gaussians, sample_standard_normal


def scatter(ax, points: torch.Tensor, title: str, color: str) -> None:
    """Draw one 2D point cloud with fixed axes for fair visual comparison."""

    pts = points.detach().cpu()
    ax.scatter(pts[:, 0], pts[:, 1], s=4, alpha=0.45, c=color, edgecolors="none")
    ax.set_title(title)
    ax.set_xlim(-3.5, 3.5)
    ax.set_ylim(-3.5, 3.5)
    ax.set_aspect("equal", adjustable="box")
    ax.grid(alpha=0.2)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--checkpoint", type=Path, default=Path("flow_matching/research_material/_outputs/minimal_2d.pt"))
    parser.add_argument("--out", type=Path, default=Path("flow_matching/research_material/figures/minimal_2d_result.png"))
    parser.add_argument("--device", type=str, default="cpu")
    parser.add_argument("--samples", type=int, default=2048)
    parser.add_argument("--trajectory-samples", type=int, default=64)
    parser.add_argument("--steps", type=int, default=64)
    parser.add_argument("--seed", type=int, default=0)
    args = parser.parse_args()

    torch.manual_seed(args.seed)
    checkpoint = torch.load(args.checkpoint, map_location=args.device)
    model = MLPVelocity(**checkpoint.get("model_config", {})).to(args.device)
    model.load_state_dict(checkpoint["model"])
    model.eval()

    source = sample_standard_normal(args.samples, device=args.device)
    target = sample_eight_gaussians(args.samples, device=args.device)
    # Generated samples are endpoints of the learned ODE flow.
    # generatedは、学習済みODE flowを最後まで解いた終点である。
    generated = euler_solve(model, source, steps=args.steps)

    traj_source = sample_standard_normal(args.trajectory_samples, device=args.device)
    # return_trajectory=True gives (time, batch, dim), useful for drawing paths.
    # return_trajectory=Trueにすると、軌道描画用に(time, batch, dim)を返す。
    trajectory = euler_solve(model, traj_source, steps=args.steps, return_trajectory=True).cpu()

    fig, axes = plt.subplots(2, 2, figsize=(9, 9), constrained_layout=True)
    scatter(axes[0, 0], source, "source: standard normal", "#4C78A8")
    scatter(axes[0, 1], target, "target: eight Gaussians", "#F58518")
    scatter(axes[1, 0], generated, "generated by Euler sampler", "#54A24B")

    ax = axes[1, 1]
    for i in range(trajectory.shape[1]):
        path = trajectory[:, i, :]
        ax.plot(path[:, 0], path[:, 1], linewidth=0.8, alpha=0.45, color="#7A5195")
    ax.scatter(trajectory[0, :, 0], trajectory[0, :, 1], s=8, alpha=0.5, c="#4C78A8", label="t=0")
    ax.scatter(trajectory[-1, :, 0], trajectory[-1, :, 1], s=8, alpha=0.5, c="#54A24B", label="t=1")
    ax.set_title("sample trajectories")
    ax.set_xlim(-3.5, 3.5)
    ax.set_ylim(-3.5, 3.5)
    ax.set_aspect("equal", adjustable="box")
    ax.grid(alpha=0.2)
    ax.legend(frameon=False, loc="upper right")

    args.out.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(args.out, dpi=180)
    print(f"saved: {args.out}")


if __name__ == "__main__":
    main()
