"""学習済み diffusion baseline から DDIM sampling を行い、分布を描画する。

同じ eight-Gaussians toy problem を使うことで、Flow Matching の ODE sampling と
diffusion の反復的 denoising を視覚的に比較できる。
"""

import argparse
from pathlib import Path

import matplotlib.pyplot as plt
import torch

from fm_minimal import MLPVelocity, ddim_sample, sample_eight_gaussians, sample_standard_normal


def scatter(ax, points: torch.Tensor, title: str, color: str) -> None:
    pts = points.detach().cpu()
    ax.scatter(pts[:, 0], pts[:, 1], s=4, alpha=0.45, c=color, edgecolors="none")
    ax.set_title(title)
    ax.set_xlim(-3.5, 3.5)
    ax.set_ylim(-3.5, 3.5)
    ax.set_aspect("equal", adjustable="box")
    ax.grid(alpha=0.2)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--checkpoint",
        type=Path,
        default=Path("flow_matching/research_material/_outputs/diffusion_toy.pt"),
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=Path("flow_matching/research_material/figures/diffusion_toy_result.png"),
    )
    parser.add_argument("--device", type=str, default="cpu")
    parser.add_argument("--samples", type=int, default=2048)
    parser.add_argument("--trajectory-samples", type=int, default=64)
    parser.add_argument("--steps", type=int, default=64)
    parser.add_argument("--seed", type=int, default=0)
    args = parser.parse_args()

    torch.manual_seed(args.seed)
    checkpoint = torch.load(args.checkpoint, map_location=args.device)
    model = MLPVelocity(**checkpoint.get("model_config", {})).to(args.device)
    model.load_state_dict(checkpoint["model"])
    model.eval()

    source = sample_standard_normal(args.samples, device=args.device)
    target = sample_eight_gaussians(args.samples, device=args.device)
    generated = ddim_sample(model, source, steps=args.steps)

    trajectory_source = sample_standard_normal(args.trajectory_samples, device=args.device)
    trajectory = ddim_sample(
        model,
        trajectory_source,
        steps=args.steps,
        return_trajectory=True,
    ).cpu()

    fig, axes = plt.subplots(2, 2, figsize=(9, 9), constrained_layout=True)
    scatter(axes[0, 0], source, "source: standard normal", "#4C78A8")
    scatter(axes[0, 1], target, "target: eight Gaussians", "#F58518")
    scatter(axes[1, 0], generated, "generated by DDIM-style sampler", "#54A24B")

    ax = axes[1, 1]
    for index in range(trajectory.shape[1]):
        path = trajectory[:, index, :]
        ax.plot(path[:, 0], path[:, 1], linewidth=0.8, alpha=0.45, color="#7A5195")
    ax.scatter(trajectory[0, :, 0], trajectory[0, :, 1], s=8, c="#4C78A8", label="noise")
    ax.scatter(trajectory[-1, :, 0], trajectory[-1, :, 1], s=8, c="#54A24B", label="generated")
    ax.set_title("reverse diffusion trajectories")
    ax.set_xlim(-3.5, 3.5)
    ax.set_ylim(-3.5, 3.5)
    ax.set_aspect("equal", adjustable="box")
    ax.grid(alpha=0.2)
    ax.legend(frameon=False, loc="upper right")

    args.out.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(args.out, dpi=180)
    plt.close(fig)
    print(f"saved: {args.out}")


if __name__ == "__main__":
    main()
